### ISSUE TITLE
Add two  index by using the nexus style

### ISSUE THREAD

**Issue by zenon-bit** [alexisflesch/nexus#4]
Hello,

I try to add two indexes using the nexus style. I had some succefull to creat these indexes. Infortunately, the nexus style consider the indexes as a part of the last chapter (the foot of pages of the indexes are pointing on the last chapter by the heigh rectangle in the foot), while the head page is correct (with the correct title of each index). 

I want to know if you have a solution about this. Than you in advance for your response.

**Comment by alexisflesch** [comment]
Hi,

I'm not sure I fully understand your problem ? It might be not that hard to fix though. Could you please provide a MWE ? I will try to get to it eventually but things are crazy this month for me so it won't be before 2021.

**Comment by zenon-bit** [comment]
Thank you for your reply. Finally, I was able to solve my index problem. However, when I use the titletoc package to get minitoc in each chapter, something is wrong because I get the same main toc in each chapter. Following the titletoc documentation, just put ` \ startcontents [sections] \ printcontents [sections] {} {1} {\ section * {minitoc}}`

 at the beginning of each chapter. I am using the test file presented in your nexus project. I am not in too much of a hurry and I understand the current concerns. Either way, I need to resolve this issue before February 2021.
En savoir plus sur ce texte source

**Comment by alexisflesch** [comment]
Did your problem come from my package or was it on your end ? Maybe giving hints on how to solve it will help someone in the future.

Also, it seems like you're still experiencing an issue. If it is not related to this one, please open a new one and provide a MWE.
