### ISSUE TITLE
Some strange and may be a bug of TOC

### ISSUE THREAD

**Issue by assjock** [alexisflesch/nexus#5]
There's some thing strang about my TOC when I use nexus style. If I split my tex file into some parts and use \include to join them together, the index will become a part of the last chapter. I don't think this is because of hyperref. Just like this.
![a](https://user-images.githubusercontent.com/28192604/187021727-a6102628-fcef-4a39-bb27-10dcc5ddec99.png)

I split the MWE into 3 parts since I need to use \include.

main.tex:
```code
\documentclass[11pt,oneside]{book}
\usepackage[palette=munch]{nexus}
\usepackage{hyperref}
\begin{document}
\tableofcontents
\chapter{This is a Chapter}
\include{1.tex}
\chapter{This is a Chapter}
\include{2.tex}
\end{document}
```
 and 1.tex:
```code
\section{1}
```

2.tex:
```code
\section{2}
```

But if I write \chapter and \section together, this won't happen.
Just like:
main.tex:
```code
\documentclass[11pt,oneside]{book}
\usepackage[palette=munch]{nexus}
\usepackage{hyperref}
\begin{document}
\tableofcontents
\include{1.tex}
\include{2.tex}
\include{3.tex}
\end{document}
```
 and 1.tex:
```code
\chapter{This is a Chapter}
\section{1}
```

2.tex:
```code
\chapter{This is a Chapter}
\section{2}
```

3.tex:
```code
\section{3}
```

**Comment by alexisflesch** [comment]
There is definitely something strange going on : I also found some issues using appendices and couldn't figure out where it came from. This is how I deal with it in my main.tex file : 

``
\begin{document}
\include{titlepage}
\tableofcontents
\cleardoublepage

\include{chapter1/chapter1}
\include{chapter2/chapter2}
...

\cleardoublepage
\begin{appendices}
    \input{appendix}
\end{appendices}`
``

Hope this helps. I don't know how to fix this the right way though (I've tried -a lot-), I know this is frustrating but I don't have a solution.

**Comment by assjock** [comment]
I found this problem troublesome. This is because \include{} will start a new page. To make the TOC work well, I have to add some other thing into the first page of the chapter or use \input{}. This is not the bug of nexus style but some thing have to do with \@makechapterhead

**Comment by assjock** [comment]
Thanks for your reply!😀
